[package]
name = "pixiv"
version = "0.2.0"
description = "Unofficial rust library for the Pixiv API."
keywords = ["pixiv", "pixiv-api"]
repository = "https://github.com/fairingrey/rustpixiv"
authors = ["Allen Bui <allenbui94@gmail.com>"]
license = "MIT"

[dependencies]
reqwest = { version = "0.9" }
bytes = "0.4"
http = "0.1"
serde = "1"
serde_json = "1.0.11"
serde_urlencoded = "0.5"
chrono = "0.4"
log = "0.3"
dotenv = "0.15.0"
md5 = "0.7.0"
url = "2.1.1"